version: '3.1'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "3000:3000"
    command: >
      npm start
